"use client";

import {
  Activity,
  AlertCircle,
  Award,
  Bell,
  ArmchairIcon,
  ArrowLeft,
  CalendarCheck,
  CalendarDays,
  CalendarPlus,
  CalendarX,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Clock,
  Dumbbell,
  Eye,
  EyeOff,
  Flame,
  Heart,
  HeartPulse,
  Home,
  Instagram,
  ListChecks,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Megaphone,
  MinusCircle,
  Pencil,
  Phone,
  Plus,
  Repeat,
  Save,
  Search,
  SearchX,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Tag,
  Target,
  Trash2,
  TrendingUp,
  Undo2,
  User,
  UserCheck,
  UserPlus,
  UserSearch,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

/**
 * Los nombres siguen la nomenclatura de Material Symbols usada en el diseño
 * y se resuelven contra el set de Lucide React, que viaja en el bundle.
 */
const ICONOS: Record<string, LucideIcon> = {
  add: Plus,
  arrow_back: ArrowLeft,
  badge: Award,
  campaign: Megaphone,
  calendar_add_on: CalendarPlus,
  calendar_month: CalendarDays,
  call: Phone,
  chair: ArmchairIcon,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  delete: Trash2,
  diversity_3: Users,
  do_not_disturb_on: MinusCircle,
  error: AlertCircle,
  event: CalendarDays,
  event_available: CalendarCheck,
  event_busy: CalendarX,
  fitness_center: Dumbbell,
  local_fire_department: Flame,
  favorite: Heart,
  target: Target,
  group: Users,
  home: Home,
  groups: Users,
  how_to_reg: UserCheck,
  location_on: MapPin,
  logout: LogOut,
  mail: Mail,
  menu: Menu,
  edit: Pencil,
  monitor_heart: HeartPulse,
  notifications: Bell,
  person: User,
  person_add: UserPlus,
  person_search: UserSearch,
  photo_camera: Instagram,
  repeat: Repeat,
  rule: ListChecks,
  save: Save,
  schedule: Clock,
  search: Search,
  search_off: SearchX,
  sell: Tag,
  self_improvement: Sparkles,
  shield_person: ShieldCheck,
  tune: SlidersHorizontal,
  trending_up: TrendingUp,
  undo: Undo2,
  visibility: Eye,
  visibility_off: EyeOff,
};

/** Opciones curadas para el selector de icono de un pilar del método. */
export const ICONOS_PILARES = [
  { valor: "fitness_center", etiqueta: "Pesas" },
  { valor: "self_improvement", etiqueta: "Movilidad" },
  { valor: "monitor_heart", etiqueta: "Ritmo cardiaco" },
  { valor: "diversity_3", etiqueta: "Grupo" },
  { valor: "local_fire_department", etiqueta: "Intensidad" },
  { valor: "favorite", etiqueta: "Bienestar" },
  { valor: "target", etiqueta: "Objetivo" },
  { valor: "trending_up", etiqueta: "Progreso" },
  { valor: "schedule", etiqueta: "Constancia" },
  { valor: "shield_person", etiqueta: "Acompañamiento" },
] as const;

export function Icono({
  nombre,
  size = 18,
  className = "",
}: {
  nombre: string;
  size?: number;
  className?: string;
}) {
  const Componente = ICONOS[nombre] ?? Activity;
  return <Componente aria-hidden size={size} strokeWidth={1.6} className={`shrink-0 ${className}`} />;
}
